var NSGPT=NSGPT||function(){var d=window,n={},e={prebidding:!1,adchannel:"",responsive:!0,gpttimeout:600,zdbburl:"//ns.zdbb.net/nsgpt.jsonp",libraries:["http://native.sharethrough.com/assets/tag.js"],forceReflow:!1,adpath:"/4585/ns.codingforums/",oop:["skin","stitials"],autostart:!0,adrecovery:!1,zdbeaconurl:"//track.netshelter.net/async/js/sites/codingforums.com-async.js",atfthreshold:700,maxads:!1},u={leaderboard:{size:[728,90],pos:"atf",collapse:!1,refreshonviewable:45,sizemap:{"700x100":[728,
90],"0x0":[300,250]}},billboard:{size:[[728,90],[970,250],[970,180],[970,90],[997,123]],pos:"atf",collapse:!0,refreshonviewable:45,sizemap:{"997x250":[[728,90],[997,123],[970,250],[970,180],[970,90]],"970x250":[[728,90],[970,250],[970,180],[970,90]],"700x100":[728,90],"0x0":[[320,50],[300,250]]}},rectangle:{size:[300,250],collapse:!1,sizemap:null,refreshonviewable:45},largerectangle:{size:[[336,280],[300,250]],collapse:!1,sizemap:null,refreshonviewable:45},halfpage:{size:[[300,250],[300,600]],collapse:!1,
sizemap:null,refreshonviewable:45},portrait:{size:[[300,600],[300,1050],[300,250]],collapse:!1,sizemap:null,refreshonviewable:45},skyscraper:{size:[[120,600],[160,600]],collapse:!1,sizemap:null,refreshonviewable:45},footer:{size:[[970,90],[728,90],[997,123],[970,180]],pos:"btf",collapse:!1,refreshonviewable:45,sizemap:{"970x125":[[970,90],[728,90],[997,123]],"700x100":[[728,90]],"0x0":[[320,50],[300,250]]}},"native":{size:[1,1],collapse:!0,sizemap:null,refreshonviewable:!1}},F=!1,I=[],C=e.adpath&&
-1!=e.adpath.indexOf("/4585/zd.")?{cmn:"zd"}:{},w="https:"==d.location.protocol?"https:":"http:",y=window!=window.top&&window.frameElement?!0:!1,M=!1,p=null,r=0,q=0,G={},da=function(){return"xxxxxxxxxxxyxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})},z=function(a){return a?a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""):""},k=function(a,b,c){if(F&&"undefined"!==typeof console&&console.log)try{b?console.log("[NSGPT]["+(b.id?b.id:b)+"]: "+a):
console.log("[NSGPT]: "+a),c&&console.log(c)}catch(d){}},N=function(a){a&&setTimeout(function(){try{var b=a.style.display;a.style.display="none";a.style.display=b;d.dispatchEvent(new Event("resize"))}catch(c){}},2E3)},v=function(a){return JSON.stringify(a)},ea=function(a,b){if(!d.googletag||!d.googletag.apiReady||a)if(!d.document.getElementById("ns-bts-g")||a){var c=d.document.createElement("script");c.type="text/javascript";c.async="true";c.id="ns-bts-g";c.src=w+"//www.googletagservices.com/tag/js/gpt.js";
c.onerror=function(){d.document.getElementById("ns-bts-g1")||(c.id="ns-bts-g1");NSGPT.loadGPT()};var f=d.document.getElementsByTagName("script")[0];f.parentNode.insertBefore(c,f);"undefined"!==typeof pbjs&&(pbjs.initAdserverSet=!0)}},H=function(a,b){if(e.zdbeaconurl&&!y&&!d.document.getElementById("ns-bts-zdt"))if(d.document.body){var c=document.createElement("script");c.type="text/javascript";c.async="true";c.id="ns-bts-zdt";var f=w+e.zdbeaconurl;c.src=b&&window._sp_&&window._sp_.getSafeUri?window._sp_.getSafeUri(f):
f;c.onerror=function(){d.document.getElementById("ns-bts-zdt1")||(c.id="ns-bts-zdt1");NSGPT.loadZDT()};try{d.document.body.appendChild(c)}catch(l){setTimeout(H,50)}}else setTimeout(H,50)},O=function(a,b){if(!n||!n.zdid||a){if((a||b)&&d.document.getElementById("ns-bts-zdbb")){var c=d.document.getElementById("ns-bts-zdbb");c.id="ns-bts-zdbb-old";c.parentNode.removeChild(c)}if(y&&parent.NSGPT&&parent.NSGPT.zdbbData&&parent.NSGPT.zdbbData.zdid)n=parent.NSGPT.zdbbData;else if(!d.document.getElementById("ns-bts-zdbb")){c=
document.createElement("script");c.type="text/javascript";c.async="true";c.id="ns-bts-zdbb";var f=w+e.zdbburl+"?u="+encodeURIComponent(d.parent.location.href);c.src=b&&window._sp_&&window._sp_.getSafeUri?window._sp_.getSafeUri(f):f;c.onerror=function(){d.document.getElementById("ns-bts-zdbb1")||(c.id="ns-bts-zdbb1");NSGPT.loadZDBB()};f=d.document.getElementsByTagName("script")[0];f.parentNode.insertBefore(c,f)}}},W=function(a,b){if(a){var c="nsgpt-ldr-"+a.replace(/\W+/g," ");if(!(d.document.getElementById(c)||
d.document&&d.document.querySelector&&d.document.querySelector('[src*="'+a+'"]'))){var f=d.document.createElement("script");f.type="text/javascript";f.async="true";f.id=c;-1==a.indexOf("://")&&(a=w+a);f.src=a;c=d.document.getElementsByTagName("script")[0];c.parentNode.insertBefore(f,c)}}},fa=function(){try{for(var a=document.getElementsByTagName("script"),b=a.length,c=0;c<b;c++)a[c]&&a[c].src&&-1!=a[c].src.indexOf("partner.googleadservices.com/gpt/pubads_impl")&&(a[c].onload=null,a[c].onerror=null,
a[c].parentNode.removeChild(a[c]))}catch(e){k("GPT pubads unload warning - "+e)}d.googletag&&(d.googletag.pubads&&(d.googletag.pubads().disableInitialLoad(),d.googletag.pubads().clear(),d.googletag.pubads().clearCategoryExclusions(),d.googletag.pubads().clearTagForChildDirectedTreatment()),d.googletag.impl&&(d.googletag.impl=null),d.googletag.pubads&&(d.googletag.pubads=null),d.googletag.defineSlot=null,d.googletag.defineOutOfPageSlot=null,d.googletag.enableServices=null,d.google_persistent_state&&
(d.google_persistent_state=null));d.googletag=null;d.googletag={};d.googletag.cmd=[];b=A();I=[];for(c=0;c<b.length;c++)if(a=b[c])k("Resetting adslot",a),!a._gptSlot&&a.parentNode&&a.parentNode._gptSlot&&(a=a.parentNode),a._gptSlot&&(a._gptSlot=null),a._nsgptWatchdog&&(clearTimeout(a._nsgptWatchdog),a._nsgptWatchdog=null),a._refreshOnViewableTimeout&&(clearTimeout(a._refreshOnViewableTimeout),a._refreshOnViewableTimeout=null),a._refreshOnRenderedTimeout&&(clearTimeout(a._refreshOnRenderedTimeout),
a._refreshOnRenderedTimeout=null),a._refreshOnViewable&&(a._refreshOnViewable=null,a._refreshOnRendered=null);for(var f=document.getElementsByTagName("iframe"),b=f.length,c=0;c<b;c++)(a=f[c])&&a.id&&0==a.id.indexOf("google_ads_iframe_")&&(0==a.parentNode.id.indexOf("google_ads_iframe_")&&(a=a.parentNode),a.parentNode.removeChild(a));f=document.getElementsByTagName("iframe");b=f.length;for(c=0;c<b;c++)(a=f[c])&&a.id&&0==a.id.indexOf("google_ads_iframe_")&&(0==a.parentNode.id.indexOf("google_ads_iframe_")&&
(a=a.parentNode),a.parentNode.removeChild(a))},ga=function(){if(e.adrecovery&&e.adrecovery.indexOf&&-1==e.adrecovery.indexOf("//")&&!d._sp_){d.sp_cid="kpwbBOFeVRnEVFP";var a=d.document.createElement("script");a.type="text/javascript";a.async="async";a.id="ns-bts-sp";a.src=w+e.adrecovery;a.onerror=function(){d.document.getElementById("ns-bts-sp1")||(a.id="ns-bts-sp1");NSGPT.bootstrap()};var b=d.document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}},ha=function(){ga();d&&d.document&&
d.document.addEventListener&&d.document.addEventListener("sp.blocking",X);d._sp_&&d._sp_.checkState&&d._sp_.checkState(function(a){a&&X()})},X=function(a){1<q||(q=1,O(!1,!0),d.googletag&&d.googletag.apiReady&&d.googletag.enableServices(),q=2,P())},P=function(){if(!(2<q)){1<r&&(r=1);if(e.adchannel&&"homepage"!=e.adchannel&&"general"!=e.adchannel||!d.googletag||!d.googletag.apiReady)e.adchannel||(e.adchannel="homepagedoor");else for(var a=d.googletag.pubads().getSlots(),b=0;b<a.length;b++)if(a[b]){var c=
a[b].getAdUnitPath();if(-1!=c.indexOf(e.adpath))try{if(e.adchannel=c.split("/")[c.split("/").length-1].split("_")[0],e.adchannel)break}catch(f){}a[b].getTargeting("template")&&(C.template=a[b].getTargeting("template"))}fa();d._sp_.dfp.loadGPT();q=3;setTimeout(function(){d.googletag.cmd.push(function(){window.NSGPT.setupAdslots();d.googletag.pubads().enableAsyncRendering();d.googletag.pubads().enableSingleRequest();d.googletag.pubads().setCentering(!0);d.googletag.enableServices()});d.googletag.cmd.push(Q)},
10);return!0}},Q=function(){3>q?P():5<q||(d.googletag&&d.googletag.pubadsReady&&n&&n.zdid?(window.NSGPT.renderAds(),q+=1):(d.googletag&&d.googletag.apiReady&&d.googletag.enableServices(),setTimeout(Q,20)))},Y=function(a){try{k("Prebidder Responses",null,a);var b=d.location.hostname,c;for(c in a)if(a.hasOwnProperty(c)){var f=function J(a){return a?(a^16*Math.random()>>a/4).toString(16):([1E7]+-1E3+-4E3+-8E3+-1E11).replace(/[018]/g,J)}(),e=a[c]&&a[c].bids?a[c].bids.length:0;e||k("No bids found for "+
c);for(var g=0;g<e;g++)try{var h=a[c].bids[g],m="NA",n=h.bidderCode?h.bidderCode:"",p=h.cpm?h.cpm:"",q=h.adId?h.adId:"",r=h.adUnitCode?h.adUnitCode:"",u=h.timeToRespond?h.timeToRespond:"",t=h.statusMessage?h.statusMessage:"",x=0;0!=h.cpm&&(x=h.adserverTargeting.hb_pb,m=h.size);(new Image).src=w+"//zdbb.net/l/EBd3N5GSEeWA3CIAC7Ppng?bidder="+n+"&provider=prebid&site="+b+"&cpm="+p+"&bsid="+f+"&bid="+x+"&adid="+q+"&adunit="+r+"&size="+m+"&ttr="+u+"&status="+encodeURIComponent(t)}catch(v){k("prebidder ZDBB error: "+
v)}}}catch(A){k("prebidder error: "+A)}},ia=function(){if(!e.prebidding)return!1;pbjs.bidderSettings={standard:{alwaysUseBid:!1,adserverTargeting:[{key:"hb_bidder",val:function(a){return a.bidderCode}},{key:"hb_adid",val:function(a){return a.adId}},{key:"hb_pb",val:function(a){return 200<a.cpm?(10*Math.floor(Math.min(parseInt(a.cpm),500)/10)).toFixed(2):40<a.cpm?Math.floor(a.cpm).toFixed(2):30<a.cpm?(Math.floor(10*a.cpm)/10).toFixed(2):a.cpm.toFixed(2)}},{key:"hb_size",val:function(a){return a.size}},
{key:"hb_cpm",val:function(a){return a.cpm}}]}};pbjs.que.push(function(){var a=[],b=e.adchannel||"general",c;for(c in e.prebidding){var d=b;"undefined"===typeof e.prebidding[c][d]&&(d="default");a.push({bidder:c,params:e.prebidding[c][d]})}pbjs.addAdUnits([{sizes:u.billboard.size,code:"nsgpt-billboard-1",bids:[{bidder:"appnexus",params:e.prebidding[c]["default"]}]},{sizes:u.leaderboard.size,code:"nsgpt-leaderboard-1",bids:a},{sizes:u.rectangle.size,code:"nsgpt-rectangle-1",bids:[{bidder:"appnexus",
params:e.prebidding[c]["default"]}]},{sizes:u.halfpage.size,code:"nsgpt-halfpage-1",bids:a}]);G["nsgpt-billboard-1"]=!0;G["nsgpt-leaderboard-1"]=!0;G["nsgpt-halfpage-1"]=!0;G["nsgpt-rectangle-1"]=!0;pbjs.requestBids({timeout:800,bidsBackHandler:function(a){Y(a)}})})},ja=function(a){a&&a.id&&a._gptSlot&&pbjs.que.push(function(){pbjs.requestBids({timeout:800,adUnitCodes:[a.id],bidsBackHandler:function(b){Y(bidResponse);pbjs.setTargetingForGPTAsync([a.id]);D([a],null,!0)}})})},x=function(a,b,c){var d=
a.dataset&&"undefined"!==typeof a.dataset[b]?a.dataset[b]:a.getAttribute("data-"+b);if(null===d||"null"===d||"undefined"===d)if(c)try{var e=R(a),d=u[e][b];"undefined"===typeof d&&(d=null);return d}catch(g){return null}else return null;d&&d.toLowerCase&&"true"===d.toLowerCase()?d=!0:d&&d.toLowerCase&&"false"===d.toLowerCase()?d=!1:d&&d.indexOf&&(-1!=d.indexOf("{")||-1!=d.indexOf("["))&&(d="undefined"!==typeof JSON?JSON.parse(d):eval("("+d+")"));return d},R=function(a){if(a._nsSlotName)return a._nsSlotName;
var b=a.dataset&&a.ns?a.dataset.ns:a.getAttribute("data-ns");if(!b)return k("Missing NS param",a),"";b=z(b).toLowerCase();if("mediumrectangle"==b||"mrec"==b)b="rectangle";"adsense"==b&&(b="largerectangle");"hpu"==b&&(b="halfpage");"outofpage"==b&&(b="oop");"sky"==b&&(b="skyscraper");"sharethrough"==b&&(b="native");"lb"==b&&(b="leaderboard");return a._nsSlotName=b},K=function(a){var b=a?x(a,"channel"):e.adchannel;null===b&&(b=e.adchannel);b||(b="");e.adpath&&0===e.adpath.indexOf("/4585/")||(e.adpath=
"/4585/");"/"!=e.adpath.substr(e.adpath.length-1)&&(e.adpath+="/");if(a&&-1!=e.adpath.indexOf("/4585/zd.")){var c=a.id;a.getAttribute&&a.getAttribute("data-pos")?b=b+"_"+a.getAttribute("data-pos").toUpperCase():-1==c.indexOf("Top")&&-1==c.indexOf("ad401-")&&-1==c.indexOf("ad403-")||-1!=b.indexOf("_ATF")?-1==c.indexOf("Bottom")&&-1==c.indexOf("ad414-")&&-1==c.indexOf("ad415-")||-1!=b.indexOf("_BTF")?-1!=c.indexOf("Content")&&-1==b.indexOf("_ATF2")?(b+="_ATF2",a.setAttribute("data-pos","atf")):-1!=
c.indexOf("Native")&&-1==b.indexOf("_native")&&(b+="_native"):(b+="_BTF",a.setAttribute("data-pos","btf")):(b+="_ATF",a.setAttribute("data-pos","atf"))}return e.adpath+b},Z=function(a){var b=x(a,"size",!0);a=[];if("string"===typeof b){for(var b=-1!=b.indexOf(",")?b.split(","):b.split(";"),c=0;c<b.length;c++){var d=b[c].split("x");a.push([parseInt(d[0]),parseInt(d[1])])}if(1==a.length)return a[0]}else b&&(a=b);return a},A=function(){var a=[];if(document.querySelectorAll){var b=document.querySelectorAll("div[data-ns]");
if(!b||!b.length)return a;for(var c=0;c<b.length;c++)a.push(b[c])}else if(window.jQuery)a=window.jQuery("div[data-ns]").get();else for(b=document.getElementsByTagName("div"),c=0;c<b.length;c++)b[c].getAttribute("data-ns")&&a.push(b[c]);return a.indexOf||a.length?a:[]},L=function(){return"undefined"!==typeof d.document.hidden?d.document.hidden.toString():d.document.hasFocus()?"false":"true"},aa=function(){e.gptsyncmode?d.googletag.pubads().enableSyncRendering():(d.googletag.pubads().enableAsyncRendering(),
d.googletag.pubads().enableSingleRequest());googletag.pubads().setTargeting("ctx","unprocessed").setTargeting("ipx","unprocessed");F&&googletag.pubads().setTargeting("debug","true");for(var a in n)null!==n[a]&&d.googletag.pubads().setTargeting(a,n[a]);if(d.location.search&&-1!=d.location.search.indexOf("special")){var b=d.location.search.match(/(\?|&)special=([^&]*)/);d.googletag.pubads().setTargeting("special",b?b[2]:"")}if(C)for(a in C)null!==C[a]&&d.googletag.pubads().setTargeting(a,C[a]);"undefined"!==
typeof pbjs&&pbjs.libLoaded&&(k("Prebidder: setup page targeting"),pbjs.setTargetingForGPTAsync())},S=function(a,b,c){!b&&a._gptSlot&&(b=a._gptSlot);var d=R(a);try{if(d&&u[d]&&u[d].targeting)for(var l in u[d].targeting)u[d].targeting[l]&&(b=b.setTargeting(l,u[d].targeting[l]))}catch(n){}if(d=x(a,"targeting",!1))for(l in d)d[l]&&(b=b.setTargeting(l,d[l]));if(d=x(a,"sharethrough",!1))b=b.setTargeting("sharethrough","true"),b=b.setTargeting("strnativekey",d),W("//native.sharethrough.com/assets/tag.js");
if(c)for(l in c)c[l]&&(b=b.setTargeting(l,c[l]));b=b.setTargeting("OOF",L());if(a&&-1==a.id.indexOf("nsgpt-oop-"))try{var g;if(a._gptPos)g=a._gptPos;else{var h=x(a,"pos",!0);if("string"===typeof h&&h)g=h;else{var m=a.getBoundingClientRect(),p=document.body,q=document.documentElement,r=Math.round(m.top+(window.pageYOffset||q.scrollTop||p.scrollTop)-(q.clientTop||p.clientTop||0));try{g=r<e.atfthreshold||r<screen.height/2?"atf":"btf"}catch(n){g=null}}}c=g;"string"===typeof c&&c&&(a._gptPos=c,a.setAttribute("data-pos",
c),b=b.setTargeting("ppos",c.toLowerCase()).setTargeting("pos",c.toLowerCase()))}catch(n){k(n,a)}return b},T=function(a,b){d.googletag.pubadsReady&&k("WARNING: AdSlot setup started after gpt enableServices() invoked. Please reviese your non-netshelter GPT tags");if(!b){if(4<r||d.googletag.pubadsReady)return;if(d.document.readyState&&"loading"==d.document.readyState&&!M)return k("Waiting for DOM or timeout before setting up slots"),!1;if(!n||!n.zdid)return k("Waiting for ZDBB data before setting up slots"),
!1}a||(a=A());k("Start page scan & adslot setup",null,a);if(2>r){if(!q&&e.oop)for(var c=0;c<e.oop.length;c++){var f=e.oop[c]?e.oop[c]:c+1,l="nsgpt-oop-"+f;if(!document.getElementById(l)){var g=d.document.createElement("div");g.id=l;g.className="nsgpt-oop";g.style.position="absolute";g.style.left="0px";g.style.bottom="0px";g.dataset.ns="oop";g.setAttribute("data-ns","oop");d.document.body.appendChild(g);var h=d.googletag.defineOutOfPageSlot(K(),l).addService(googletag.pubads()),h=S(g,h,{OOP_type:f});
g._gptSlot=h;I.push(g._gptSlot);k("Setup OOP adslot "+l,g)}}k("Setup GPT callbacks");googletag.pubads().addEventListener("slotRenderEnded",ka);googletag.pubads().addEventListener("impressionViewable",ba);r=2}for(c=0;c<a.length;c++)if(f=a[c],!f._gptSlot&&(l=R(f))){if(!f.id){g=f;a:{for(var h="nsgpt-"+l,m=1;10>m;m++){var p=h+"-"+m;if(!d.document.getElementById(p)){h=p;break a}}h=void 0}g.id=h}if(g="undefined"!==typeof u[l]?u[l]:null){h=d.googletag.defineSlot(K(f),Z(f),f.id);try{if(e.responsive){var t;
var v=x(f,"sizemap",!0);if(v){var w=d.googletag.sizeMapping(),m=void 0;for(m in v)var y=m.toLowerCase().split("x"),w=w.addSize([parseInt(y[0]),parseInt(y[1])],v[m]);t=w?w.build():null}else t=null;t&&(h=h.defineSizeMapping(t))}}catch(B){k(B,f)}try{var C=x(f,"collapse",!0);null!==C&&(h=h.setCollapseEmptyDiv(C))}catch(B){k(B,f)}try{if(e.prebidding&&(m=f,e.prebidding&&m&&!m._prebidding&&m.id&&-1==m.id.indexOf("nsgpt-oop"))){if("undefined"===typeof G[m.id]){var p=[],F=e.adchannel||"general",z=void 0;for(z in e.prebidding){var J=
F;"undefined"===typeof e.prebidding[z][J]&&(J="default");p.push({bidder:z,params:e.prebidding[z][J]})}var H=[{sizes:Z(m),code:m.id,bids:p}];pbjs.addAdUnits(H);G[m.id]=!0}m._prebidding=!0}}catch(B){k(B,f)}S(f,h,{rfr:"false"});f._refreshOnRendered=null;f._refreshOnViewable=null;try{var E="undefined"!==typeof g.refresh?g.refresh:null;g&&f._gptPos&&"atf"==f._gptPos&&"undefined"!==typeof g.refreshatf&&(E=g.refreshatf);E&&"string"===typeof E&&(E=parseInt(E));E&&(f._refreshOnRendered=1E3*E)}catch(B){k(B,
f)}try{var D=x(f,"refreshonviewable",!0);D&&parseInt(D)&&(f._refreshOnViewable=1E3*parseInt(D))}catch(B){k(B,f)}f._gptSlot=h.addService(googletag.pubads());k("Setup adslot "+l+" - RefreshOnViewable: "+f._refreshOnViewable+" - Refresh On Rendered: "+f._refreshOnRendered,f);I.push(f._gptSlot)}else k("Unkown config: "+l)}3>r&&(aa(),r=3);d.googletag.pubadsReady||d.googletag.enableServices()},U=function(a){if(d.document.readyState&&"loading"==d.document.readyState&&!M)k("Waiting for DOM or timeout before rendering");
else if(n&&n.zdid)if(!e.prebidding||"undefined"===typeof pbjs||pbjs.libLoaded&&pbjs.allBidsAvailable()){if(3>r||!I)try{T(null,!0)}catch(g){return k("slotsetup error: "+g),!1}if(!d.googletag.pubadsReady)try{e.gptsyncmode||(d.googletag.pubads().enableAsyncRendering(),d.googletag.pubads().enableSingleRequest(),d.googletag.pubads().setCentering(!0)),d.googletag.enableServices()}catch(g){k("Warning while init rendering - "+g)}if(!a||!a.length)a=A();else if(a.id||a.parentNode)a=[a];for(var b=0;b<a.length;b++){var c=
a[b];if(c&&!c._gptRendered)if(!c._gptSlot&&c.parentNode&&c.parentNode._gptSlot&&(c=c.parentNode),c._gptSlot){var f=-1!=c.id.indexOf("nsgpt-oop-")?!0:!1;window.getComputedStyle(c);if(!q&&!f&&d.getComputedStyle){var l=d.getComputedStyle(c);if("none"===l.display||"hidden"===l.visibility){k("Render: skipping invisible element",c);continue}}q?k("Rendering adrecovered slot",c):k("Rendering adslot",c);try{d.googletag.display(c.id)}catch(g){k("GPT error while rendering: "+g,c);continue}c._gptRendered=!0;
q||f||c._nsgptWatchdog||(c._nsgptWatchdog=setTimeout(function(){k("NSGPT Watchdog forces a refresh for stale ad",c);NSGPT.refreshAds([c])},45E3))}else q||k("Render: missing gptslot in "+c.id)}r=5}else setTimeout(U,200);else k("Waiting for ZDBB data before rendering")},t=function(a){M=!0;d.googletag.cmd.push(function(){T()});d.googletag.cmd.push(function(){U()})},D=function(a,b,c){if(d.googletag.pubadsReady){if(!a)a=A();else if(a.id||a.parentNode)a=[a];b||(b=d.__ZDDMP&&d.__ZDDMP.NewCorrelator?__ZDDMP.NewCorrelator():
da());for(var f=[],l=0;l<a.length;l++){var g=a[l];if(g&&(!g._gptSlot&&g.parentNode&&g.parentNode._gptSlot&&(g=g.parentNode),g._gptSlot)){if(e.prebidding&&!c)return ja(g);var h=g._gptSlot;h.clearTargeting();h=S(g,h,{zc:b,rfr:"true"});g._nsgptRendered=null;g._nsgptViewable=null;g._refreshOnViewableTimeout&&(clearTimeout(g._refreshOnViewableTimeout),g._refreshOnViewableTimeout=null);g._refreshOnRenderedTimeout&&(clearTimeout(g._refreshOnRenderedTimeout),g._refreshOnRenderedTimeout=null);g._nsgptWatchdog&&
(clearTimeout(g._nsgptWatchdog),g._nsgptWatchdog=null);q||(g._nsgptWatchdog=setTimeout(function(){k("NSGPT Watchdog force a refresh for stale ad",g);NSGPT.refreshAds([g])},45E3));f.push(h);k("Issue refresh command",g)}}f&&d.googletag.pubads().refresh(f)}},ca=function(a){if(!a)a=A();else if(a.id||a.parentNode)a=[a];for(var b=0;b<a.length;b++){var c=a[b];c&&(!c._gptSlot&&c.parentNode&&c.parentNode._gptSlot&&(c=c.parentNode),c._gptSlot&&(c._refreshOnViewable=null,c._refreshOnRendered=null,c._refreshOnViewableTimeout&&
(clearTimeout(c._refreshOnViewableTimeout),c._refreshOnViewableTimeout=null),c._refreshOnRenderedTimeout&&(clearTimeout(c._refreshOnRenderedTimeout),c._refreshOnRenderedTimeout=null),c._nsgptWatchdog&&(clearTimeout(c._nsgptWatchdog),c._nsgptWatchdog=null),k("Refresh stopped",c)))}},ba=function(a){var b=d.document.getElementById(a.slot.getSlotElementId());b&&!b._gptSlot&&b.nextSibling&&b.nextSibling._gptSlot&&(b=b.nextSibling);if(b&&b._gptSlot&&(b._nsgptViewable=Math.floor((new Date).getTime()),b._nsgptRendered||
(b._nsgptRendered=b.nsgptViewable),b._refreshOnViewable||b._refreshOnViewableOverride)){a=b._refreshOnViewableOverride?b._refreshOnViewableOverride:b._refreshOnViewable;var c=Math.floor(b._nsgptViewable-b._nsgptRendered);c>a?(k("Slot viewable after "+a+"ms threshold - refreshing immediately",b),D([b])):(c=Math.floor(a-c),b._refreshOnViewableTimeout=setTimeout(function(){NSGPT.refreshAds([b])},c),k("Slot viewable, but "+a+"ms threashold not hit yet - schedule a refresh in "+c+"ms",b))}},ka=function(a){var b=
d.document.getElementById(a.slot.getSlotElementId());b&&!b._gptSlot&&b.nextSibling&&b.nextSibling._gptSlot&&(b=b.nextSibling);if(b&&b._gptSlot){b._nsgptRendered=Math.floor((new Date).getTime());b._nsgptViewable=null;b._nsgptWatchdog&&(clearTimeout(b._nsgptWatchdog),b._nsgptWatchdog=null);if(b._refreshOnRendered){var c=a.isEmpty?2E3:b._refreshOnRendered;b._refreshOnRenderedTimeout=setTimeout(function(){NSGPT.refreshAds([b])},c);k("Slot rendered, set refresh timeout at "+c+"ms",b)}else k("Slot Rendered",
b);e.forceReflow&&(N(b),setTimeout(function(){N(b)},1E3));if(y&&window.frameElement&&a.size)try{window.frameElement.width=a.size[0],window.frameElement.height=a.size[1]}catch(f){}}},V=function(){if(!e.gptsyncmode)return!1;n&&n.zdid&&aa();if(e.oop)for(var a=0;a<e.oop.length;a++){var b=e.oop[a]?e.oop[a]:a+1,c="nsgpt-oop-"+b;document.getElementById(c)||(d.googletag.defineOutOfPageSlot(K(),c).setTargeting("OOF",L()).setTargeting("OOP_type",b).addService(googletag.pubads()),k("Setup Syncronous OOP adslot "+
c))}r=3};return{adSlots:I,isIframe:y,zdbbData:n,config:e,init:function(a){if(y){e.oop=!1;try{parent&&parent.NSGPT&&parent.NSGPT.config&&(e.adchannel=parent.NSGPT.config.adchannel)}catch(h){}}p||(p=d.document.getElementById("nsgpt"));if(p){for(var b=["ns","channel"],c=0;c<b.length;c++){var f=b[c],l=p.dataset&&"undefined"!==typeof p.dataset[f]?p.dataset[f]:p.getAttribute("data-"+f);if(l){e.adchannel=z(l);k("init: adchannel override: "+g);break}}l=p.dataset&&"undefined"!==typeof p.dataset.responsive?
p.dataset.responsive:p.getAttribute("data-responsive");null!==l&&(e.responsive="true"==z(l).toLowerCase()?!0:!1);l=p.dataset&&"undefined"!==typeof p.dataset.oop?p.dataset.oop:p.getAttribute("data-oop");if(null!==l){var g=z(l).toLowerCase();k("init: OOP config override: "+g);e.oop="false"==g||"0"==g||""==g?[]:g.split(",")}}if(a&&!a.target){for(f in a)e[f]=a[f];a.w&&a.w.top&&(d=a.w)}!e.adchannel&&d.location&&(e.adchannel=d.location.pathname&&"/"==d.location.pathname?"homepage":"general",k("init: adchannel autodetected: "+
e.adchannel));!d.location.search||-1==d.location.search.indexOf("nsgptdebug")&&-1==d.location.search.indexOf("googfc")||(F=1);y&&parent.location.search&&(-1!=parent.location.search.indexOf("nsgptdebug")||-1!=parent.location.search.indexOf("googfc"))&&(F=1);H();if(e.gptsyncmode){if(!(1<r)){"undefined"!==typeof JSON&&"undefined"!==typeof JSON.stringify||document.write('<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/json2/20150503/json2.min.js">\x3c/script>');try{!n.zdid&&parent&&
parent.NSGPT&&(n=parent.NSGPT.zdbbData)}catch(h){}n&&n.zdid?V():document.write('<script type="text/javascript" src="'+e.zdbburl+"?u="+encodeURIComponent(d.parent.location.href)+'">\x3c/script>');r=2}}else NSGPT.bootstrap()},bootstrap:function(){O();e.autostart&&ea();e.adrecovery&&ha();if(e.libraries)for(var a=0;a<e.libraries.length;a++)W(e.libraries[a]);e.prebidding&&ia();if(e.autostart&&!e.gptsyncmode&&(d.googletag=d.googletag||{},d.googletag.cmd=d.googletag.cmd||[],d.googletag.cmd.push(function(){d.googletag.pubads().enableAsyncRendering();
d.googletag.pubads().enableSingleRequest();d.googletag.pubads().setCentering(!0);e.gpttimeout&&!e.prebidding&&setTimeout(t,e.gpttimeout)}),!(0<r))){r=1;a=d.document&&d.document.readyState?d.document.readyState:null;if("complete"===a){if(e.prebidding){setTimeout(t,500);return}return t()}"interactive"===a?e.prebidding?setTimeout(t,500):t():a&&"loading"!==a||(d.jQuery?d.jQuery(t):d.document.addEventListener&&d.document.addEventListener("DOMContentLoaded",t,!1));if(d.addEventListener)d.addEventListener("load",
t,!1);else{var b=d.onload;d.onload=function(){try{t()}catch(a){}b&&b()}}}},forceReflow:N,loadZDBB:O,initZDBB:function(a,b){for(var c in a)n[c]=a[c];if(b)for(c in b)e[c]=b[c];if(e.gptsyncmode)return V();e.autostart&&(d.googletag=d.googletag||{},d.googletag.cmd=d.googletag.cmd||[],d.googletag.cmd.push(function(){window.NSGPT.renderAds()}))},loadZDT:H,startSP:P,renderSP:Q,getAdSlots:A,setupAdslots:T,renderAds:U,displayAds:t,refreshAds:D,stopRefresh:ca,updateRefresh:function(a,b,c){if(!a)a=A();else if(a.id||
a.parentNode)a=[a];if(!b&&!c)return ca(a);for(var d=0;d<a.length;d++){var e=a[d];!e._gptSlot&&e.parentNode._gptSlot&&(e=e.parentNode);if(b){e._refreshOnViewableTimeout&&(clearTimeout(e._refreshOnViewableTimeout),e._refreshOnViewableTimeout=null);if(e._nsgptViewable){var g=Math.floor((new Date).getTime())-e._nsgptViewable;g<b?D([e]):e._refreshOnViewableTimeout=setTimeout(function(){NSGPT.refreshAds([e])},Math.floor(b-g))}else e._refreshOnViewableOverride=b;k("New RefreshOnViewable ("+b+") set",e)}c&&
(e._refreshOnRenderedTimeout&&(clearTimeout(e._refreshOnRenderedTimeout),e._refreshOnRenderedTimeout=null),e._refreshOnRenderedTimeout=setTimeout(function(){NSGPT.refreshAds([e])},1E3*c),k("New RefreshOnViewable ("+c+") set",e))}},onViewable:ba,onLoaded:function(a){},detectOOF:L,adserve:function(a,b,c,f){n&&n.zdid||document.write('<script type="text/javascript" src="'+e.zdbburl+"?u="+encodeURIComponent(d.parent.location.href)+'">\x3c/script>');var k=K(),g=u[a];a=v(g.size);var h=['.setTargeting("OOF", '+
v(L())+")",'.setTargeting("rfr", "false")'];c&&(h.push('.setTargeting("pos", "'+c+'")'),h.push('.setTargeting("ppos", "'+c+'")'));b=b?'.setClickUrl("'+b+'")':"";for(var m in n)null!==n[m]&&h.push('.setTargeting("'+m+'", '+v(n[m])+")");d.location.search&&-1!=d.location.search.indexOf("special")&&(c=d.location.search.match(/(\?|&)special=([^&]*)/),h.push('.setTargeting("special", "'+(c?c[2]:"")+'")'));if(g.targeting)for(m in g.targeting)null!==g.targeting[m]&&h.push('.setTargeting("'+m+'", '+v(g.targeting[m])+
")");if(f)for(m in f)null!==f[m]&&h.push('.setTargeting("'+m+'", '+v(f[m])+")");g.sizemap&&d.document&&d.document.documentElement&&d.document.documentElement.clientWidth&&(f=document.documentElement.clientWidth,m=-1!=d.location.hostname.indexOf("androidforums.com")?1330:1E3,f<m&&(a=700<f?v([728,90]):v([[300,250],[320,50]])));b='<center><script src="//www.googletagservices.com/tag/js/gpt.js">googletag.pubads().definePassback("'+k+'", '+a+")"+h.join("")+b+".display();\x3c/script></center>";document.write(b);
return!0},setupSyncSlots:V,renderSyncSlots:function(){if(!e.oop||!e.gptsyncmode)return!1;for(var a=['<script type="text/javascript">googletag.enableServices();\x3c/script>'],b=0;b<e.oop.length;b++){var c="nsgpt-oop-"+(e.oop[b]?e.oop[b]:b+1);document.getElementById(c)||(k("Render Syncronous OOP adslot "+c),a.push('<div id="'+c+'" style="position: absolute; left: 0px; bottom: 0px;"><script type="text/javascript">googletag.display("'+c+'")\x3c/script></div>'))}document.write(a.join(""))}}}();
"undefined"!==typeof window._NSGPT?NSGPT.init(window._NSGPT):NSGPT.init();
